#!/usr/bin/env zsh
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env zsh
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias per="cd ~/personal"

alias zpr="$VIM $DOTFILES/.zprofile"
alias zrc="$VIM $DOTFILES/.zshrc"
alias doti="dotFileInstall && source ~/.zshrc"

alias yolo="git push origin main --force --no-verify"
alias dotFileInstall="$DOTFILES/install"

